linear:
	gcc -g -o linear linear.c ../images/imageprocessing.o ../conv/line_conv.o -I ../images -I ../conv -lfreeimage
gauss:
	gcc -g -o linear gaussian_test.c ../images/imageprocessing.o ../conv/line_conv.o -I ../images -I ../conv -lfreeimage -I ../gauss
